ReportDir = "$HOME/.config/daily/reports"
TemplateFile = "$HOME/.config/daily/template.md"
PluginDir = "$HOME/.config/daily/plugins"
Editor = "code"

[Serve]
TemplateBodyFile = "$HOME/.config/daily/index.html"
AssetsDir = "$HOME/.config/daily/assets"