ReportDir = "$HOME/.config/daily/reports"
TemplateFile = "$HOME/.config/daily/template.md"
PluginDir = "$HOME/.config/daily/plugins"
Editor = "code"

[Serve]
TemplateIndexFile = "$HOME/.config/daily/index.tmpl"
TemplateBodyFile = "$HOME/.config/daily/index.tmpl"
AssetsDir = "$HOME/.config/daily/assets"